# Demyx
# https://demyx.sh

notifications:
  email:
    on_success: never
    on_failure: always

services:
  - docker

env:
  - DEMYX_USERNAME=demyx DEMYX_REPOSITORY=code-server

before_install:
  - docker pull debian:buster-slim
  - docker pull docker
  - docker pull golang:buster
  - docker pull koalaman/shellcheck
  - docker pull php:7-fpm-buster
  - docker pull quay.io/vektorlab/ctop

script:
  - docker build --no-cache -t demyx/"$DEMYX_REPOSITORY":bedrock tag-bedrock
  - docker build --no-cache -t demyx/"$DEMYX_REPOSITORY":browse tag-browse
  - docker build --no-cache -t demyx/"$DEMYX_REPOSITORY":go tag-go
  - docker build --no-cache -t demyx/"$DEMYX_REPOSITORY":latest tag-latest
  - docker build --no-cache -t demyx/"$DEMYX_REPOSITORY":openlitespeed tag-openlitespeed
  - docker build --no-cache -t demyx/"$DEMYX_REPOSITORY":openlitespeed-bedrock tag-openlitespeed-bedrock
  - docker build --no-cache -t demyx/"$DEMYX_REPOSITORY":wp tag-wp
  - docker run -dit --name="$DEMYX_REPOSITORY" demyx/"$DEMYX_REPOSITORY"
  - docker exec "$DEMYX_REPOSITORY" code-server --version

after_success:
  - /bin/echo "$DEMYX_PASSWORD" | docker login -u "$DEMYX_USERNAME" --password-stdin
  - docker push demyx/"$DEMYX_REPOSITORY":bedrock
  - docker push demyx/"$DEMYX_REPOSITORY":browse
  - docker push demyx/"$DEMYX_REPOSITORY":go
  - docker push demyx/"$DEMYX_REPOSITORY":latest
  - docker push demyx/"$DEMYX_REPOSITORY":openlitespeed
  - docker push demyx/"$DEMYX_REPOSITORY":openlitespeed-bedrock
  - docker push demyx/"$DEMYX_REPOSITORY":tag-wp
  - bash travis.sh
